### ISSUE TITLE
【準機能要件】管理画面を作る

### ISSUE THREAD

**Issue by kumackey** [kumackey/book-output#117]
まだ管理するリソースの数は少ないし、管理画面を今のうちに作っておきたい

Userにis_adminカラムを付ける

ひとまず欲しい機能
- 既存の本の情報を変えられる
- 既存のauthorsの情報を変えられる
- User一覧が見れる
- Userの情報を変えられる

**Comment by t1gerk1ngd0m** [comment]
管理画面系のgemはいくつかあるので、練習としてgemを使うでもいいし、管理画面自体を丸ごと自分で作るでもいいですね。
コントローラーやルーティングのnamespaceの練習にもなります。

**Comment by kumackey** [comment]
調べたらgemいっぱいありますね！
namespaceはマイページ機能の際に使ったりしたので、今回は素直にgemで考えようかなと思いました。
active_adminで考えてます！

**Comment by kumackey** [comment]
参考記事
https://kossy-web-engineer.hatenablog.com/entry/2018/09/05/060905
https://ccbaxy.xyz/blog/2019/11/08/ruby12/
https://masaru-tech.hateblo.jp/entry/2017/04/21/142234
